name: Deploy to dist-pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0        # 拿到完整历史，才能推 orphan 分支

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js & Cache pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install & Build all packages
        run: |
          pnpm install
          pnpm -r build

      - name: Debug ls
        run: ls -R packages/web

      - name: Publish to dist-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packages/web/dist
          publish_branch: dist-pages
